[phases.setup]
nixPkgs = [
    "python3", 
    "gcc", 
    "pkg-config",
    "libGL",
    "libglib",
    "glib",
    "libxext",
    "libxrender",
    "libgomp"
]

[phases.install]
cmds = [
    "python -m venv --copies /opt/venv",
    ". /opt/venv/bin/activate && pip install --upgrade pip",
    ". /opt/venv/bin/activate && pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python minimal_start.py"

[variables]
PYTHONPATH = "/app/src"
ENVIRONMENT = "production"
# 设置OpenCV使用headless模式
OPENCV_IO_ENABLE_OPENEXR = "0"
OPENCV_IO_ENABLE_JASPER = "0" 